### ISSUE TITLE
Provide alternatives to GitHub login

### ISSUE THREAD

**Issue by FerPerales** [magmaconf/cfp-magmarails-com#25]
Some people asked if GitHub login was the only way to send a paper and I'm concern about that:

I know GitHub is a very popular service, but what if I don't have an account or I don't want to use it for authentication purposes?

Shall we provide another alternative such the classic email/password registration?

**Comment by mumoc** [comment]
I remember this discussion some years ago, with the first Magmarails. What we define at that time is that, if you don't have a Github account then why we should caer about your proposals? I know, it sounds stupid, but the fact was we were trying to "filter" by default those people who doesn't participate in open source projects or are pretty much in the same channel as we are. 

On that time, RoR was mainstream and for "surely" if you have an important topic of Rails, you "surely" will have a Github account.

But, given the change of the "main line" of MagmaConf, I'm joining your questions, shall we provide another alternative? 

@jacques, @softr8 ???

**Comment by joiggama** [comment]
Closing, as [v2016.0.0](https://github.com/magmaconf/cfp-magmarails-com/releases/tag/v2016.0.0) already supports alternate authentication method with google.
